export const ROOT = 'https://shift-backend.onrender.com';
export const OTP = `${ROOT}/auth/otp`;
export const USERS = `${ROOT}/users`;
export const SIGNIN = `${USERS}/signin`;
export const PROFILE = `${USERS}/profile`;
export const SESSION = `${USERS}/session`;
export const DELIVERY = `${ROOT}/delivery`;
export const POINTS = `${DELIVERY}/points`;
export const PACKAGE_TYPES = `${DELIVERY}/package/types`;
export const CALC = `${DELIVERY}/calc`;
export const ORDER = `${DELIVERY}/order`;
export const ORDERS = `${DELIVERY}/orders`;
export const SPECIAL_ORDER = (id: string) => `${ORDERS}/${id}`;
export const CANCEL = `${ORDERS}/cancel`;
